USE PracticaMega
GO


-- Llenar tabla colonias con 20 colonias por ciudad (ciudades principales)
INSERT INTO colonias (nombre, ciudad_id, abrevCiudad) VALUES 
-- Guadalajara (ciudad_id = 121) - 20 colonias
('Centro Histórico', 121, 'CH-GDL'),
('Americana', 121, 'AM-GDL'),
('Providencia', 121, 'PROV-GDL'),
('Chapultepec', 121, 'CHAP-GDL'),
('Vallarta Norte', 121, 'VN-GDL'),
('Jardines del Bosque', 121, 'JB-GDL'),
('Chapalita', 121, 'CHA-GDL'),
('Santa Teresita', 121, 'ST-GDL'),
('Arcos Vallarta', 121, 'AV-GDL'),
('Colinas de San Javier', 121, 'CSJ-GDL'),
('Las Águilas', 121, 'LA-GDL'),
('Residencial Victoria', 121, 'RV-GDL'),
('Monraz', 121, 'MON-GDL'),
('Zona Rosa', 121, 'ZR-GDL'),
('Del Valle', 121, 'DV-GDL'),
('Constitución', 121, 'CONST-GDL'),
('Oblatos', 121, 'OBL-GDL'),
('Huentitán', 121, 'HUEN-GDL'),
('Minerva', 121, 'MIN-GDL'),
('Miravalle', 121, 'MIR-GDL'),

-- Zapopan (ciudad_id = 122) - 20 colonias
('Zapopan Centro', 122, 'ZC-ZAP'),
('Puerta de Hierro', 122, 'PH-ZAP'),
('Residencial Poniente', 122, 'RP-ZAP'),
('Ciudad Granja', 122, 'CG-ZAP'),
('Lomas del Valle', 122, 'LV-ZAP'),
('Real de Tesistán', 122, 'RT-ZAP'),
('Miramar', 122, 'MIR-ZAP'),
('La Calma', 122, 'LC-ZAP'),
('Arboledas', 122, 'ARB-ZAP'),
('Tabachines', 122, 'TAB-ZAP'),
('Bosques de la Victoria', 122, 'BV-ZAP'),
('Villa Universitaria', 122, 'VU-ZAP'),
('Prados Providencia', 122, 'PP-ZAP'),
('Nuevo México', 122, 'NM-ZAP'),
('Francisco I. Madero', 122, 'FIM-ZAP'),
('Lomas de Zapopan', 122, 'LZ-ZAP'),
('Parques de Tesistán', 122, 'PT-ZAP'),
('Mesa Colorada', 122, 'MC-ZAP'),
('San Juan de Ocotán', 122, 'SJO-ZAP'),
('Nextipac', 122, 'NEX-ZAP'),

-- León (ciudad_id = 101) - 20 colonias
('Centro', 101, 'CEN-LEO'),
('Jardines de Jerez', 101, 'JJ-LEO'),
('San Miguel', 101, 'SM-LEO'),
('La Martinica', 101, 'MAR-LEO'),
('Los Paraísos', 101, 'LP-LEO'),
('Residencial Campestre', 101, 'RC-LEO'),
('Valle del Campestre', 101, 'VC-LEO'),
('Hidalgo', 101, 'HID-LEO'),
('Del Recreo', 101, 'DR-LEO'),
('La Floresta', 101, 'FLO-LEO'),
('Lomas del Campestre', 101, 'LC-LEO'),
('Panorama', 101, 'PAN-LEO'),
('San Felipe de Jesús', 101, 'SFJ-LEO'),
('Piletas', 101, 'PIL-LEO'),
('Bellavista', 101, 'BV-LEO'),
('Azteca', 101, 'AZT-LEO'),
('Santa Ana del Conde', 101, 'SAC-LEO'),
('Villa de Guadalupe', 101, 'VG-LEO'),
('Pedregal de Haciendas', 101, 'PH-LEO'),
('Las Torres', 101, 'LT-LEO'),

-- Monterrey (ciudad_id = 181) - 20 colonias
('Centro de Monterrey', 181, 'CM-MTY'),
('Santa Catarina', 181, 'SC-MTY'),
('Obispado', 181, 'OB-MTY'),
('Mitras Centro', 181, 'MC-MTY'),
('Del Valle', 181, 'DV-MTY'),
('Roma', 181, 'ROM-MTY'),
('Industrial', 181, 'IND-MTY'),
('Moderna', 181, 'MOD-MTY'),
('Buenos Aires', 181, 'BA-MTY'),
('Residencial San Agustín', 181, 'RSA-MTY'),
('Contry', 181, 'CON-MTY'),
('Cumbres', 181, 'CUM-MTY'),
('Linda Vista', 181, 'LV-MTY'),
('Mirador', 181, 'MIR-MTY'),
('Independencia', 181, 'IND-MTY'),
('Doctores', 181, 'DOC-MTY'),
('Terminal', 181, 'TER-MTY'),
('Ancira', 181, 'ANC-MTY'),
('Cerro de la Silla', 181, 'CS-MTY'),
('Apodaca Centro', 181, 'AC-MTY'),

-- Puebla (ciudad_id = 201) - 20 colonias
('Centro Histórico', 201, 'CH-PUE'),
('La Paz', 201, 'LP-PUE'),
('Angelópolis', 201, 'ANG-PUE'),
('Jardines de San Manuel', 201, 'JSM-PUE'),
('Bosques de Angelópolis', 201, 'BA-PUE'),
('San Jerónimo Caleras', 201, 'SJC-PUE'),
('Zavaleta', 201, 'ZAV-PUE'),
('Universidad', 201, 'UNI-PUE'),
('Agua Santa', 201, 'AS-PUE'),
('El Carmen', 201, 'EC-PUE'),
('Bugambilias', 201, 'BUG-PUE'),
('Villa Carmel', 201, 'VC-PUE'),
('Flor del Bosque', 201, 'FB-PUE'),
('Santa Cruz Buenavista', 201, 'SCB-PUE'),
('Granjas San Isidro', 201, 'GSI-PUE'),
('Cleotilde Torres', 201, 'CT-PUE'),
('Bosques de San Sebastián', 201, 'BSS-PUE'),
('Maravillas', 201, 'MAR-PUE'),
('Villa Frontera', 201, 'VF-PUE'),
('Real de San Andrés', 201, 'RSA-PUE'),

-- Tijuana (ciudad_id = 21) - 20 colonias
('Zona Centro', 21, 'ZC-TIJ'),
('Zona Río', 21, 'ZR-TIJ'),
('Playas de Tijuana', 21, 'PT-TIJ'),
('La Mesa', 21, 'LM-TIJ'),
('Otay', 21, 'OT-TIJ'),
('Libertad', 21, 'LIB-TIJ'),
('Cacho', 21, 'CAC-TIJ'),
('Hipódromo', 21, 'HIP-TIJ'),
('Chapultepec', 21, 'CHA-TIJ'),
('Camino Verde', 21, 'CV-TIJ'),
('Villa Fontana', 21, 'VF-TIJ'),
('Las Palmas', 21, 'LP-TIJ'),
('Lomas de Agua Caliente', 21, 'LAC-TIJ'),
('Colinas de California', 21, 'CC-TIJ'),
('Reforma', 21, 'REF-TIJ'),
('Buenaventura', 21, 'BV-TIJ'),
('Soler', 21, 'SOL-TIJ'),
('Aviación', 21, 'AV-TIJ'),
('Mariano Matamoros', 21, 'MM-TIJ'),
('Alemán', 21, 'ALE-TIJ'),

-- Mérida (ciudad_id = 301) - 20 colonias
('Centro Histórico', 301, 'CH-MER'),
('García Ginerés', 301, 'GG-MER'),
('Itzimná', 301, 'ITZ-MER'),
('México', 301, 'MEX-MER'),
('Buenavista', 301, 'BV-MER'),
('Campestre', 301, 'CAM-MER'),
('San José Tecoh', 301, 'SJT-MER'),
('Francisco de Montejo', 301, 'FM-MER'),
('Montes de Amé', 301, 'MA-MER'),
('Residencial Colonia México', 301, 'RCM-MER'),
('Pedregales de Tanlum', 301, 'PT-MER'),
('Dzityá', 301, 'DZI-MER'),
('Chuburná', 301, 'CHU-MER'),
('Altabrisa', 301, 'ALT-MER'),
('Las Américas', 301, 'LA-MER'),
('Benito Juárez Norte', 301, 'BJN-MER'),
('San Antonio Cinta', 301, 'SAC-MER'),
('Vergel', 301, 'VER-MER'),
('Salvador Alvarado Sur', 301, 'SAS-MER'),
('Sodzil Norte', 301, 'SN-MER'),

-- Cancún (ciudad_id = 221) - 20 colonias
('Centro', 221, 'CEN-CUN'),
('Zona Hotelera', 221, 'ZH-CUN'),
('SM 21', 221, 'SM21-CUN'),
('SM 23', 221, 'SM23-CUN'),
('SM 25', 221, 'SM25-CUN'),
('SM 77', 221, 'SM77-CUN'),
('Residencial Cumbres', 221, 'RC-CUN'),
('Las Américas', 221, 'LA-CUN'),
('Supermanzana 29', 221, 'SM29-CUN'),
('Supermanzana 50', 221, 'SM50-CUN'),
('Puerto Juárez', 221, 'PJ-CUN'),
('Región 100', 221, 'R100-CUN'),
('Región 240', 221, 'R240-CUN'),
('Alfredo V. Bonfil', 221, 'AVB-CUN'),
('Ciudad Caucel', 221, 'CC-CUN'),
('Villas Otoch Paraíso', 221, 'VOP-CUN'),
('Gran Santa Fe', 221, 'GSF-CUN'),
('Residencial Palmaris', 221, 'RP-CUN'),
('Jardines del Sur', 221, 'JS-CUN'),
('Paraíso Maya', 221, 'PM-CUN'),

-- Toluca (ciudad_id = 141) - 20 colonias
('Centro', 141, 'CEN-TOL'),
('La Merced', 141, 'LM-TOL'),
('Universidad', 141, 'UNI-TOL'),
('Delegación San Lorenzo', 141, 'DSL-TOL'),
('Capultitlán', 141, 'CAP-TOL'),
('Seminario', 141, 'SEM-TOL'),
('Santa Ana Tlapaltitlán', 141, 'SAT-TOL'),
('Doctores', 141, 'DOC-TOL'),
('Morelos', 141, 'MOR-TOL'),
('5 de Mayo', 141, '5M-TOL'),
('Otzacatipan', 141, 'OTZ-TOL'),
('Santa Clara', 141, 'SC-TOL'),
('Pilares', 141, 'PIL-TOL'),
('Las Torres', 141, 'LT-TOL'),
('Residencial Colón', 141, 'RC-TOL'),
('Adolfo López Mateos', 141, 'ALM-TOL'),
('Benito Juárez', 141, 'BJ-TOL'),
('Nueva Oxtotitlán', 141, 'NO-TOL'),
('Felipe Berriozábal', 141, 'FB-TOL'),
('San Bernardino', 141, 'SB-TOL'),

-- Chihuahua (ciudad_id = 61) - 20 colonias
('Centro', 61, 'CEN-CHI'),
('Nombre de Dios', 61, 'ND-CHI'),
('San Felipe', 61, 'SF-CHI'),
('Granjas', 61, 'GRA-CHI'),
('Campestre', 61, 'CAM-CHI'),
('Cerro de la Cruz', 61, 'CC-CHI'),
('Dale', 61, 'DAL-CHI'),
('Las Haciendas', 61, 'LH-CHI'),
('Riberas de Sacramento', 61, 'RS-CHI'),
('Villa Juárez', 61, 'VJ-CHI'),
('Satelite', 61, 'SAT-CHI'),
('Quintas del Sol', 61, 'QS-CHI'),
('Los Nogales', 61, 'LN-CHI'),
('Rincones de San Marcos', 61, 'RSM-CHI'),
('San Patricio', 61, 'SP-CHI'),
('Mirador', 61, 'MIR-CHI'),
('Residencial Universidad', 61, 'RU-CHI'),
('Chula Vista', 61, 'CV-CHI'),
('Altavista', 61, 'AV-CHI'),
('Las Misiones', 61, 'LM-CHI');

-- Verificar inserción
SELECT COUNT(*) AS total_colonias FROM colonias;

-- Ver colonias por ciudad
SELECT 
    c.nombre AS ciudad,
    e.nombre AS estado,
    COUNT(col.id) AS total_colonias
FROM colonias col
INNER JOIN ciudades c ON col.ciudad_id = c.id
INNER JOIN estados e ON c.estados_id = e.id
GROUP BY c.nombre, e.nombre
ORDER BY total_colonias DESC;